title: YUKI.CFG
description: A config for Counter-Strike Global Offensive.
show_downloads: true
github:
  zip_url: https://github.com/rwwrou/yuki.cfg/raw/master/yukicfg.zip
theme: jekyll-theme-tactile
